
services:
  postgres:
    container_name: temporal-ai-pipeline_db
    image: ankane/pgvector
    command: postgres -c 'max_connections=200'
    ports:
      - 5432:5432
    restart: always
    environment:
       - POSTGRES_HOST_AUTH_METHOD=trust
       - POSTGRES_PASSWORD=dbpassword
       - POSTGRES_USER=dbuser
       - POSTGRES_DB=vector_db

  localstack:
    container_name: temporal-ai-pipeline_localstack
    image: localstack/localstack:s3-latest
    ports:
      - 4566:4566
    environment:
      - DEBUG=${DEBUG:-0}
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=testUser
      - AWS_SECRET_ACCESS_KEY=testAccessKey
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  n8n-worker:
    container_name: temporal_n8n_worker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NAMESPACE=${NAMESPACE}
      - TEMPORAL_HOST_URL=host.docker.internal:7233
    volumes:
      - ./src:/usr/src/app/src
    command: >
      sh -c '\
        sleep 3 \
        && npx nodemon --watch src --ext ts src/n8n/worker.ts \
      '